### ISSUE TITLE
mac环境下编译报错

### ISSUE THREAD

**Issue by qingliangcn** [jg513/enif_protobuf#1]
环境：
macOS 10.12.6
Erlang 18.3

报错内容很长，不贴了，主要问题是：
1. stack_t类型同macos中的内置类型冲突
2. 64位整数类型兼容问题（例如：ErlNifSInt64和uint_64并不是完全兼容的）

**Comment by jg513** [comment]
已经修改了。macOS 10.12.6, Erlang 19, 测试通过。Windows和Linux还未测试。

**Comment by qingliangcn** [comment]
good job :)
