### ISSUE TITLE
enum default value is being set to undefined in proto3

### ISSUE THREAD

**Issue by balusu-murali** [jg513/enif_protobuf#11]
- In proto3 format: the default value of an enum field must be the first value in the list of the possible values.
- gpb actually does this correctly.. but the nif code sets the value to be undefined.

Any suggestions on how to fix it?
I found the function to modify in ep_decoder.c. but could not figure out the exact changes to make.
any pointers would be greatly appreciated.

**Comment by jg513** [comment]
https://github.com/jg513/enif_protobuf/blob/459a5c7056a977ed9751e6662ef49c8f953b1409/c_src/ep_decoder.c#L835

pseudo-code maybe added as following:

else if (field->type == field_enum && field->proto_v == 3) {
    *t++ = field->sub_node->v_fields[0]->name
}

Hope this helps

**Comment by balusu-murali** [comment]
Thanks, I got it working.. however.. the proto_v is 2 in my case for some reason.. I use gpb to compile and obtain the msg definitions and then I load it using enif_protobuf.

**Comment by jg513** [comment]
https://github.com/jg513/enif_protobuf/blob/459a5c7056a977ed9751e6662ef49c8f953b1409/c_src/enif_protobuf.c#L184

There is a function `get_msg_defs` in the generated erl.

Is there any `proto3` or `proto3_msgs` words in the definition?

**Comment by balusu-murali** [comment]
No, I do not see one in the `get_msg_defs` function in the generated erl file.
However, my .proto files have the line `syntax=proto3`.

**Comment by jg513** [comment]
https://github.com/tomas-abrahamsson/gpb/issues/184#issue-670437556

**Comment by balusu-murali** [comment]
thank you!

**Comment by jg513** [comment]
```protobuf
syntax="proto3";

message Person {
    string name = 1;
    int32 id = 2;
    optional string email = 3;
}
```

```shell
erl -pa ebin
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.0.3  (abort with ^G)
1> gpb_compile:file("x.proto",[to_proto_defs,{proto_defs_version,2}]).
{ok,[{proto_defs_version,2},
     {file,{"x","x.proto"}},
     {{msg_containment,"x"},['Person']},
     {{enum_containment,"x"},[]},
     {syntax,"proto3"},
     {{msg,'Person'},
      [{field,name,1,2,string,defaulty,[]},
       {field,id,2,3,int32,defaulty,[]},
       {field,email,3,4,string,optional,[]}]},
     {proto3_msgs,['Person']}]}
```

Try to load_cache with the definitions

**Comment by balusu-murali** [comment]
I am trying to run `load_cache` inside my application after it starts. I use rebar to compile my proto files.. Although It works in the erl shell as you show, adding `proto_defs_version` or the `to_proto_defs` options to my rebar.config does not help.

**Comment by jg513** [comment]
Could you share the snippet in your rebar.config?

```shell
erl -noshell -pa GPB/ebin -eval 'io:format("-module(x).\n-export([get_msg_defs/0]).\nget_msg_defs() ->\n~p.",[case gpb_compile:file("x.proto",[to_proto_defs,{proto_defs_version,2}]) of {ok,V} -> V end])' -eval 'init:stop()' > defs.erl
```

The shell command will generate a defs file.

**Comment by balusu-murali** [comment]
```
{proto_opts, [
              {compiler, gpb},
              {src_dirs, ["proto"]}
             ]}.


{gpb_opts, [{msg_name_prefix, "pb_"},
            {o_erl, "src/proto/"},
            {o_hrl, "include/proto/"},
            {to_proto_defs},
            {proto_defs_version, 2}]}.
```

**Comment by jg513** [comment]
https://github.com/tomas-abrahamsson/gpb/blob/87abc9cf9ee613ac1068b2e02f54eb48e9862d39/src/gpb_compile.erl#L1246

It seems when set `to_proto_defs`, no files will be generated.

**Comment by balusu-murali** [comment]
sorry for the delay in getting back.
I removed `to_proto_defs` and use this now: it still does not help!
```
{gpb_opts, [{msg_name_prefix, "pb_"},
            {o_erl, "src/proto/"},
            {o_hrl, "include/proto/"},
            {strings_as_binaries, true},
            {proto_defs_version, 2}]}.
```

**Comment by jg513** [comment]
We must compile proto files with `to_proto_defs` option.

But with the option, we can just get the output from shell, no file will be generated.

So I think we should generate another defs file, and load the defs.

This is one possible way, I posted before:

https://github.com/jg513/enif_protobuf/issues/11#issuecomment-667613341

**Comment by jg513** [comment]
https://github.com/tomas-abrahamsson/gpb/issues/184#issuecomment-848101500

**Comment by dogtapdsd** [comment]
when I use gpb 4.18.0 with -introspect-get_proto_defs option, generate get_proto_defs like 
`get_proto_defs() ->
    [{proto_defs_version, 2},
     {file, {"proto3_180", "proto3_180.proto"}},
     {{msg_containment, "proto3_180"}, [pro_180_all_prop, pro_180_items_list]},
     {{enum_containment, "proto3_180"}, []},
     {syntax, "proto3"},
     {{msg, pro_180_items_list},
      [#field{name = id, fnum = 1, rnum = 2, type = uint32, occurrence = defaulty, opts = []},
       #field{name = num, fnum = 2, rnum = 3, type = uint32, occurrence = defaulty, opts = []},
       #field{name = text, fnum = 3, rnum = 4, type = string, occurrence = defaulty, opts = []}]},
     {{msg, pro_180_all_prop},
      [#field{name = key, fnum = 1, rnum = 2, type = uint32, occurrence = defaulty, opts = []},
       #field{name = value, fnum = 2, rnum = 3, type = uint32, occurrence = defaulty, opts = []},
       #field{name = incval, fnum = 3, rnum = 4, type = uint32, occurrence = defaulty, opts = []}]},
     {proto3_msgs, [pro_180_all_prop, pro_180_items_list]}].`

but after execute code enif_protobuf:load_cache(proto3_180:get_proto_defs()). in eshell, it crash immidiately. error like “start.sh: line 2: 24780 Segmentation fault ”
here is 
proto3_180.proto
`syntax = "proto3";
message Pro_180_Items_List {
    uint32 id = 1;                                             
    uint32 num = 2;                                               
    string text = 3;						   
}
message Pro_180_All_Prop {
    uint32 key = 1;                                                 
    uint32 value = 2;                                             
    uint32 incval = 3;
}`

**Comment by jg513** [comment]
@dogtapdsd Please try the new commit
