### ISSUE TITLE
rebar compile issue

### ISSUE THREAD

**Issue by dogtapdsd** [jg513/enif_protobuf#18]
collect2: error: ld returned 1 exit status
ERROR: sh(cc c_src/enif_protobuf.o c_src/ep_cache.o c_src/ep_decoder.o c_src/ep_encoder.o c_src/ep_node.o $LDFLAGS -shared  -L"/usr/lib64/erlang/lib/erl_interface-4.0.2/lib" -lerl_interface -lei -o priv/enif_protobuf_drv.so)
failed with return code 1 and the following output:
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status

os version = centos 7.9
erlang otp version = Erlang/OTP 23 [erts-11.1.7] 
gcc-4.8.5-44.el7.x86_64
libgcc-4.8.5-44.el7.x86_64
gcc-c++-4.8.5-44.el7.x86_64
under this path "/usr/lib64/erlang/lib/erl_interface-4.0.2/lib", only with  two files  libei_st.a libei.a

**Comment by dogtapdsd** [comment]
i have check otp 23 readme ,seen It was removed
  OTP-16328    Application(s): erl_interface

               As announced in OTP 22.0, the deprecated parts of
               erl_interface have now been removed (essentially all C
               functions with prefix erl_).

**Comment by jg513** [comment]
Sorry for late response. I will try to solve it.

**Comment by jg513** [comment]
I test it, but without any errors. Environment:

CentOS Linux release 7.9.2009 (Core)
Erlang/OTP 23 [erts-11.2]

**Comment by dogtapdsd** [comment]
==> enif_protobuf (compile)
make: Entering directory `/data/project/ranch_demo/deps/enif_protobuf/c_src'
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/lib/erlang/erts-11.2/include/ -I /usr/local/lib/erlang/lib/erl_interface-4.0.2/include  -c -o /data/project/ranch_demo/deps/enif_protobuf/c_src/enif_protobuf.o /data/project/ranch_demo/deps/enif_protobuf/c_src/enif_protobuf.c
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/lib/erlang/erts-11.2/include/ -I /usr/local/lib/erlang/lib/erl_interface-4.0.2/include  -c -o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_cache.o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_cache.c
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/lib/erlang/erts-11.2/include/ -I /usr/local/lib/erlang/lib/erl_interface-4.0.2/include  -c -o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_decoder.o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_decoder.c
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/lib/erlang/erts-11.2/include/ -I /usr/local/lib/erlang/lib/erl_interface-4.0.2/include  -c -o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_encoder.o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_encoder.c
/data/project/ranch_demo/deps/enif_protobuf/c_src/ep_encoder.c: In function ‘pack_float’:
/data/project/ranch_demo/deps/enif_protobuf/c_src/ep_encoder.c:354:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *((int32_t *) (enc->p)) = *((int32_t *) &val);
     ^
/data/project/ranch_demo/deps/enif_protobuf/c_src/ep_encoder.c: In function ‘pack_double’:
/data/project/ranch_demo/deps/enif_protobuf/c_src/ep_encoder.c:398:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *((int64_t *) (enc->p)) = *((int64_t *) &val);
     ^
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/lib/erlang/erts-11.2/include/ -I /usr/local/lib/erlang/lib/erl_interface-4.0.2/include  -c -o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_node.o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_node.c
cc /data/project/ranch_demo/deps/enif_protobuf/c_src/enif_protobuf.o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_cache.o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_decoder.o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_encoder.o /data/project/ranch_demo/deps/enif_protobuf/c_src/ep_node.o -shared -L /usr/local/lib/erlang/lib/erl_interface-4.0.2/lib -lei -lpthread -o /data/project/ranch_demo/deps/enif_protobuf/c_src/../priv/enif_protobuf.so
make: Leaving directory `/data/project/ranch_demo/deps/enif_protobuf/c_src'
Compiled src/enif_protobuf.erl
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status
ERROR: sh(cc c_src/enif_protobuf.o c_src/ep_cache.o c_src/ep_decoder.o c_src/ep_encoder.o c_src/ep_node.o $LDFLAGS -shared  -L"/usr/local/lib/erlang/lib/erl_interface-4.0.2/lib" -lerl_interface -lei -o priv/enif_protobuf_drv.so)
failed with return code 1 and the following output:
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status

ERROR: compile failed while processing /data/project/ranch_demo/deps/enif_protobuf: rebar_abort
---------------------------------------
I just try again,  get this compile error messages
With Erlang/OTP 23 [erts-11.2]

**Comment by jg513** [comment]
Can you post the Makefile inside c_src?

**Comment by dogtapdsd** [comment]
# Based on c_src.mk from erlang.mk by Loic Hoguin <essen@ninenines.eu>

CURDIR := $(shell pwd)
BASEDIR := $(abspath $(CURDIR)/..)

PROJECT ?= $(notdir $(BASEDIR))
PROJECT := $(strip $(PROJECT))

ERTS_INCLUDE_DIR ?= $(shell erl -noshell -s init stop -eval "io:format(\"~ts/erts-~ts/include/\", [code:root_dir(), erlang:system_info(version)]).")
ERL_INTERFACE_INCLUDE_DIR ?= $(shell erl -noshell -s init stop -eval "io:format(\"~ts\", [code:lib_dir(erl_interface, include)]).")
ERL_INTERFACE_LIB_DIR ?= $(shell erl -noshell -s init stop -eval "io:format(\"~ts\", [code:lib_dir(erl_interface, lib)]).")

C_SRC_DIR = $(CURDIR)
C_SRC_OUTPUT ?= $(CURDIR)/../priv/$(PROJECT).so

# System type and C compiler/flags.

UNAME_SYS := $(shell uname -s)
ifeq ($(UNAME_SYS), Darwin)
	CC ?= cc
	CFLAGS ?= -O3 -std=c99 -arch x86_64 -finline-functions -Wall -Wmissing-prototypes
	CXXFLAGS ?= -O3 -arch x86_64 -finline-functions -Wall
	LDFLAGS ?= -arch x86_64 -flat_namespace -undefined suppress
else ifeq ($(UNAME_SYS), FreeBSD)
	CC ?= cc
	CFLAGS ?= -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes
	CXXFLAGS ?= -O3 -finline-functions -Wall
else ifeq ($(UNAME_SYS), Linux)
	CC ?= gcc
	CFLAGS ?= -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes
	CXXFLAGS ?= -O3 -finline-functions -Wall
endif

CFLAGS += -fPIC -I $(ERTS_INCLUDE_DIR) -I $(ERL_INTERFACE_INCLUDE_DIR)
CXXFLAGS += -fPIC -I $(ERTS_INCLUDE_DIR) -I $(ERL_INTERFACE_INCLUDE_DIR)

LDLIBS += -L $(ERL_INTERFACE_LIB_DIR) -lei -lpthread
LDFLAGS += -shared

# Verbosity.

c_verbose_0 = @echo " C     " $(?F);
c_verbose = $(c_verbose_$(V))

cpp_verbose_0 = @echo " CPP   " $(?F);
cpp_verbose = $(cpp_verbose_$(V))

link_verbose_0 = @echo " LD    " $(@F);
link_verbose = $(link_verbose_$(V))

SOURCES := $(shell find $(C_SRC_DIR) -type f \( -name "*.c" -o -name "*.C" -o -name "*.cc" -o -name "*.cpp" \))
OBJECTS = $(addsuffix .o, $(basename $(SOURCES)))

COMPILE_C = $(c_verbose) $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE_CPP = $(cpp_verbose) $(CXX) $(CXXFLAGS) $(CPPFLAGS) -c

$(C_SRC_OUTPUT): $(OBJECTS)
	@mkdir -p $(BASEDIR)/priv/
	$(link_verbose) $(CC) $(OBJECTS) $(LDFLAGS) $(LDLIBS) -o $(C_SRC_OUTPUT)

%.o: %.c
	$(COMPILE_C) $(OUTPUT_OPTION) $<

%.o: %.cc
	$(COMPILE_CPP) $(OUTPUT_OPTION) $<

%.o: %.C
	$(COMPILE_CPP) $(OUTPUT_OPTION) $<

%.o: %.cpp
	$(COMPILE_CPP) $(OUTPUT_OPTION) $<

clean:
	@rm -f $(C_SRC_OUTPUT) $(OBJECTS)
--------------------------------------------------------------
here It is

**Comment by jg513** [comment]
Could you try again?

**Comment by dogtapdsd** [comment]
yes, It works !
