### ISSUE TITLE
What does tid_not_found mean and how to avoid it?

### ISSUE THREAD

**Issue by kpy3** [jg513/enif_protobuf#4]
Hi,

sometimes I get `tid_not_found` during data encoding, what does this error mean?

**Comment by jg513** [comment]
I am not able to reproduce the `tid_not_found` error, but I modified something about it. Can you update and have a try?

**Comment by kpy3** [comment]
Thank you, will try next week.

More info on issue: 16 cores on server, about 100000 messages per second for encode, about the same value for decode

**Comment by kpy3** [comment]
Seems it does not help much for messages bigger than two kilobytes, still have this issue. :(

**Comment by jg513** [comment]
Ok, I will try more to reproduce it.

**Comment by kpy3** [comment]
Tried to add one more field to `Person` with up to 4096 bytes data and encode it with up to `8 * Processors` (= 32) threads, but without any luck. It seems it somehow linked with our application's architecture or load profile, or something else. Going to close the issue for now. Thanks for you help.

**Comment by jg513** [comment]
I have reproduced the error, and committed a fix. Please update and have a try. Hope it's helpful.

**Comment by kpy3** [comment]
Thenk you a lot, will try it and ping you back with results.

**Comment by kpy3** [comment]
After 12+ hours on our load env, no new `tid_no_found` errors occurred, thank you very much for the fix.

**Comment by jg513** [comment]
Great, thanks for your feedback.
