### ISSUE TITLE
load_cache crash if there are other fields after oneof

### ISSUE THREAD

**Issue by bwalkowi** [jg513/enif_protobuf#6]
Hi,

it seems that load_cache crash if there are other fields after the oneof one. 
Below is example of proto that should result in fail but if you comment out `proxy_session_id` it will work.

```
syntax = "proto2";
package one.clproto;


message ServerMessage {
    oneof message_body { 
        int32 file_children = 3;
        bytes xattr = 4;
    }

    optional bytes proxy_session_id                        = 21;
}
```

**Comment by jg513** [comment]
I have committed a fix.

**Comment by bwalkowi** [comment]
thanks a lot, it now works correctly.
