### ISSUE TITLE
decoding of some msg fails

### ISSUE THREAD

**Issue by bwalkowi** [jg513/enif_protobuf#7]
Hi,

while testing `enif_protobuf` I have stumbled upon cases when decoding encoded msg returns incorrect record. 

For example, having such proto definition:
```
syntax = "proto2";
package one.clproto;


message FuseResponse {
    oneof fuse_response {
        FileChildren file_children = 3;
        bytes xattr = 13;
    }
}

message ChildLink {
    required bytes name = 2;
}

message FileChildren {
    repeated ChildLink child_links = 1;
}

message ServerMessage {
    oneof message_body {
        FuseResponse             fuse_response             = 15;
    }
}
```

after encoding following record:
```
{'ServerMessage',
    {fuse_response,
        {'FuseResponse',
            {file_children,{'FileChildren',[{'ChildLink',<<"1">>}]}}}}}
```
and decoding record shown below was returned:
```
{'ServerMessage',
    {fuse_response,{'FuseResponse',{'FileChildren',[{'ChildLink',<<"1">>}]}}}}
```

**Comment by jg513** [comment]
I fixed the issue by the minimum modification. And I think the processing of nested message should be refined later.

**Comment by bwalkowi** [comment]
sure, thanks. I will continue testing and provider feedback if I find anything else.

**Comment by bwalkowi** [comment]
After testing for some time I have not found any more errors, thanks for quick fix.
